#!/usr/bin/env bash
 

WEBAPI=vk.com

echo "UTF8 check: ☠"
#################login
echo "Logging into $WEBAPI as $USERNAME..."
#Login part 1
#printf "%s" "Logging in (1/2)..."
echo "Logging in (1/2)..."
CR=$(curl -S \
    --location \
    --retry 2 \
    --retry-delay 5\
    --cookie $cookie_jar \
    --cookie-jar $cookie_jar \
    --user-agent "Curl Shell Script" \
    --keepalive-time 60 \
    --compressed \
    --data-urlencode "lgname=${USERNAME}" \
    --data-urlencode "lgpassword=${USERPASS}" \
    --request "POST" "${WEBAPI}?action=login&format=txt")

#act=login&to=&_origin=http%3A%2F%2Fvk.com&ip_h=4736d56023f6e2c308&email=asd&pass=sda&expire=

CR2=($CR)
if [ "${CR2[9]}" = "[token]" ]; then
    TOKEN=${CR2[11]}
    echo "Logging in (1/2)...Complete"
else
    echo "Login part 1 failed."
    echo $CR
    exit
fi
 
#Login part 2
echo "Logging in (2/2)..."
CR=$(curl -S \
    --location \
    --cookie $cookie_jar \
    --cookie-jar $cookie_jar \
    --user-agent "Curl Shell Script" \
    --keepalive-time 60 \
    --header "Accept-Language: en-us" \
    --header "Connection: keep-alive" \
    --compressed \
    --data-urlencode "lgname=${USERNAME}" \
    --data-urlencode "lgpassword=${USERPASS}" \
    --data-urlencode "lgtoken=${TOKEN}" \
    --request "POST" "${WEBAPI}?action=login&format=txt")
 
#TODO-Add login part 2 check
echo "Successfully logged in as $USERNAME."
 
###############
#Get edit token
echo "Fetching edit token..."
CR=$(curl -S \
    --location \
    --cookie $cookie_jar \
    --cookie-jar $cookie_jar \
    --user-agent "Curl Shell Script" \
    --keepalive-time 60 \
    --header "Accept-Language: en-us" \
    --header "Connection: keep-alive" \
    --compressed \
    --request "POST" "${WEBAPI}?action=tokens&format=txt")
 
CR2=($CR)
EDITTOKEN=${CR2[8]}
if [ ${#EDITTOKEN} = 34 ]; then
    echo "Edit token is: $EDITTOKEN"
else
    echo "Edit token not set."
    echo $CR
    exit
fi
#########################
 

my_edit(){

if [ "$1" ] && [ "$2" ]; then
    title="$1"
    text="$(cat "$2")"
else
    echo "wiki <page> <text_file>"
    echo "example Участник:AndroidRobot ~/text"
fi

#title="Участник:AndroidRobot"
#text="$(cat text)"
#text="Hello!"

CR=$(curl -S \
    --location \
    --cookie $cookie_jar \
    --cookie-jar $cookie_jar \
    --user-agent "Curl Shell Script" \
    --keepalive-time 60 \
    --header "Accept-Language: en-us" \
    --header "Connection: keep-alive" \
    --header "Expect:" \
    --form "token=${EDITTOKEN}" \
    --form "title=$title" \
    --form "text=$text" \
    --request "POST" "${WEBAPI}?action=edit&format=txt&")

echo $CR
}

my_edit "$1" "$2"
#upload

upload(){
curl "http://bits.wikimedia.org/images/wikimedia-button.png" >wikifile

CR=$(curl -S \
    --location \
    --cookie $cookie_jar \
    --cookie-jar $cookie_jar \
    --user-agent "Curl Shell Script" \
    --keepalive-time 60 \
    --header "Accept-Language: en-us" \
    --header "Connection: keep-alive" \
    --header "Expect:" \
    --form "token=${EDITTOKEN}" \
    --form "filename=filename1.png" \
    --form "text=Filedescription" \
    --form "comment=commentDetails" \
    --form "file=@wikifile" \
    --request "POST" "${WEBAPI}?action=upload&format=txt&")
 
echo $CR
}

#read -p "Done..."
exit