#!/bin/bash

index_file="users_query.sql"

date_convert(){
    clear_date="$(echo "$1" | sed "s \(./history/\|/json\\|_parsed\|\.\)  g" | sed "s_-_ _g")" #"#310515 09:55:01
    reverse_date="$(date -d "${clear_date}" "+%d%m%y %H:%M:%S")" #150531 09:55:01
    unix_date="$(date -d "${reverse_date}" +"%s")"
    echo "$unix_date"
}

create_sql(){
    while read uid online name family photo nn; do
        my_name="$name $family"
        my_date="$(date_convert $1)"
        
        echo "INSERT INTO users (id, name, link) VALUES ($uid, '${my_name}', '${photo}');"
	echo "INSERT INTO user_online (user_id, status) VALUES ($uid, to_timestamp($my_date));"
    done < $1

}

#create_sql "./history/01.01.15/json-00:00:04_parsed"

run(){
    find ./history/ -type f -iname "json-*" -print0 | while IFS= read -r -d $'\0' line; do
	create_sql $line >>$index_file
    done
}

run